### ISSUE TITLE
Handling exceptions

### ISSUE THREAD

**Issue by pveber** [agarwal/future#3]
The signature in `future.ml` includes a `fail` function, so how about including a way to handle exceptions, like a
```ocaml
val catch : (unit -> 'a Deferred.t) -> (exn -> 'a Deferred.t) -> 'a Deferred.t
```

**Comment by agarwal** [comment]
I'll consider this issue closed from c362353b708663e43e09b3c40868e54c03cd0a2a. Please reopen if you don't think so.
